- llmware/parsers.py
TextParser and ImageParser both access `block_size_target_characters` attribute of `library` when `library is None`, they should get it from `parser.library`
> Fix bug in parsers.py

- llmware/retrieval.py
If you tried running `expand_text_result_after` on the last blockid of a document then it would get stuck in an infinite loop. This fixes it and gives the same output as you get when you run `expand_text_result_before` on blockid 0.
> Fixed infinite loop in `expand_text_result_after`

- llmware/util.py
in TextChunker.convert_text_to_chunks, the updated statement is chunking text into individual characters for short texts, causing explosion of chunks
> Fix OCR chunking into single letter chunks for text short text  #293

- llmware/util.py
In cases where the first . shows up when x < 5… 
it will fail due to the line
**_short_window = self.text_chunk[x-5:x-1]_**
after that short_window would be empty and so
_**if not 47 < ord(short_window[-1]) < 58:**_
crashes the process. with my fix I was not able to reproduce the error
> A fix to smooth_edges. 

- llmware/prompts.py
Not sure if you want to set an "unlikely" value when we can't find the `page_num`, `doc_id` or `block_id` like 999999? This might make it easier to spot if a default value was used
> Added doc_id and block_id to evidence_metadata and source_review output

- llmware/resources.py
mongodb documents are limited to 16mb. any direct result produced by mongo is considered a document and so it is limited to 16mb. this is also true for the result of a collection.distinct() operation. if there is enough documents in the mongo the result can get larger then 16mb and it will break the ingestion process. to overcome that limitation we use now a aggregate operation, that will not produce a document but a cursor and so we can retrieve a unlimited number of data from mongo. this way the number of documents that can be processed during embedding gets from a real big number to a unlimited number. limiting factors are now the available memory and time to process and the time left until the sun gets a red giant and eats our beloved earth :)
> With this we try to overcome a limitation in mongodb. 

- llmware/util.py
array out of bounds error in retrieval #453
fix the tokenize util to strip out front and back whitespace and use any whitespace instead of a single whitespace so we do not have errors in tokenization.
> fix tokenize whitespace issue (Issue #453)

- .github/workflows/pages.yml
This PR adds a trigger to the documentation workflow. In particular, it triggers the workflow whenever a pull request is closed and the docs directory has changed.
> Add pull request closed trigger for documentation workflow

- .github/workflows/pages.yml
This PR fixes the broken CI of pages by adding the correct name of the branch and adding permission to the deploy job.
> Fix broken CI of pages

- llmware/configs.py
- llmware/embeddings.py
This PR fixes the broken Pinecone implementation.
The source of the issue is likely that while the ``setup.py`` requires ``pinecone-client==3.0.0``, as evident by
https://github.com/llmware-ai/llmware/blob/3e4a9fb2387d5c0ee2982480fadee4a58e4c3870/setup.py#L83
the code itself does not conform to the Pinecone API version 3 - instead, it is on version 2.
This PR fixes this issue by updating the code to the Pinecone API version 3.
> Fix broken Pinecone implementation

- examples/Embedding/using_pinecone_openai.py
This PR fixes minor issues in the Pinecone and OpenAI example.
Specifically, it fixes a reference to a wrong parameter in a ``docstring``, and makes the messages from raised ``exceptions`` more consistent.
> Fix minor issues in Pinecone and OpenAI example

- docs/index.md
This PR improves the ``About the Project`` section in the docs.
In particular, it adds for subsection, which are
1. A subsection on how to contribute to the project,
2. A subsection on the code of conduct,
3. A subsection on the relationship between ``llmware`` and ``AI Bloks``, and finally
4. A subsection that thanks and lists all the contributors.
> Improve about the project section

- docs/Gemfile
- docs/Gemfile.lock
- docs/_config.yml
This PR fixes the broken *contributors section* on the homepage of the docs.
The contributors section was broken as I did not list the contributors. Apparently, the issue was that the plugin was not loaded, and that the variable `repository` was missing.
> Fix contributors section in docs

- docs/Gemfile
- docs/Gemfile.lock
This PR pins rexml to ```3.2.8``` to fix a security issue from an earlier version.
> Pin rexml to fix security issue

- docs/community/troubleshooting.md
- docs/getting_started/working_with_docker.md
1. Added a point to the troubleshooting doc about an issue with newer examples, where the example file must be placed in the outer-most directory with the `llmware` source code directory so that the program uses the latest source code and not the source code in `site-packages`.
2. Added instructions for setting up Docker and Docker Compose in `working-with-docker.md`.
> Documentation

- examples/SLIM-Agents/document_unique_topics_extraction.py
- examples/SLIM-Agents/youtube_topics_extraction.py
One was designed for a long document, to extract topics and collapse them, leaving only unique results.  The youtube example takes a transcript from youtube api, then does the same topic extraction Both have a minimum confidence score setting, that can be used to remove non salient topics with low confidence scores, or alternatively to cast a wider net.
> Two examples using slim topics tool

- docs/community/community.md
- docs/community/faq.md
- docs/community/join_our_community.md
- docs/community/need_help.md
- docs/community/troubleshooting.md
- docs/components/agent_inference_server.md
- docs/components/agents.md
- docs/components/components.md
- docs/components/data_stores.md
- docs/components/embedding_models.md
This PR fixes typos on certain pages on the LLMWare Docs Site.
N/A
> docs: Fix typos on certain pages of the LLMWare Docs Site

- README.md
This PR adds small model benchmarking, Qwen2/Phi-3 integrations, BizBot, WhisperCPP transcription, OCR for embedded images, advanced document parsing, and optimized RAG prompts, enhancing functionality and deployment ease.
> Update README.md with latest enhancements, new models, use cases

- .gitignore
- llmware/model_configs.py
- llmware/models.py
added the following claude models in the modelCatalog:
Claude 3 Haiku: A smaller, faster Claude 3 version introduced in March 2024. Lower latency for simpler tasks, accessible through Anthropic’s API.
Claude 3.5 Haiku: Released in October 2024. Matches most of Claude 3 Opus’s performance but keeps the speed of the earlier Haiku model.
Claude 3.5 Sonnet: An enhanced Claude 3 Sonnet, also from October 2024, with notable improvements in coding and tool use.
Claude 3.7 Sonnet: Released February 2025, supports up to a 200k token context and features advanced hybrid reasoning. Outperforms previous 3.x Claude models.
All these models are driven by message API
> feat && fix: added new models to modelCatalog, updated .gitignore to ignore .env files

- jupyter notebooks/Agents Fast Start/Agents_01.ipynb
- jupyter notebooks/Agents Fast Start/Agents_02.ipynb
- jupyter notebooks/Agents Fast Start/Agents_03.ipynb
Here are a few new notebooks for the Agents fast start. Another batch is coming soon!
All these notebooks are tested and are running fine!!
CC: @doberst
> feat: added new notebooks of agents fast start

- llmware/models.py
This pull request introduces a new `MultiModalModel` class to the `llmware/models.py` file, designed to support multi-modal models that handle various data types like text and images. It includes methods for preprocessing, postprocessing, and performing inference across different model types, such as PyTorch, ONNX, OpenVINO, TensorFlow, and GGUF.
Related Issue: #1025
* **Class overview**: Added the `MultiModalModel` class to manage multi-modal models, with attributes for model name, type, and optional preprocessors and postprocessors.
* **Preprocessing and postprocessing**: Introduced methods `add_preprocessor`, `add_postprocessor`, `preprocess`, and `postprocess` to handle data transformations for specific data types.
* **Inference logic**: Implemented the `inference` method to …
> Add MultiModalModel class for handling multi-modal data processing and inference
