CONTRIBUTING.md, README.md
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.
=> docs(grammatical): correct typos and improve grammar

llmware/library.py
add_file method now give the same return value as add_files so caller can receive info about the added file.
=> Update add_file to return output

llmware/retrieval.py
Added ability to see whether matched values, or primary and secondary.
Also updated the `text_results` to pull from the correct dictionary.
=> Update dual_pass_query to include primary or secondary match keys

llmware/status.py, tests/run-tests.py
2 Changes :
1.Embedding status thread does not terminate #236
2.tests/run-tests.py takes 'localhost' as host for Milvus, it can be taken from environment variable. In my own setup , I dont use localhost as milvus server
=> Embedding status thread does not terminate #236

llmware/retrieval.py
Added the ability to do a dual_pass_query with a custom filter (and in turn semantic_query). I've found this to be a powerful tool for pulling back the right data. Unsure if it conforms to your format but I've tried to keep it in line as much as possible. Have tested with a few different queries and pulls back correct results with / without a custom filter.
=> Semantic search with custom filter

README.md
Simply changed around some grammar for improved readability.
=> Grammar Update README.md

examples/Getting_Started/ui_without_a_database.py
**Testing**
- ![image](https://github.com/llmware-ai/llmware/assets/17209734/3be36810-683b-4953-8435-f428774e131c)
=> make web-ui in streamlit to run basic RAG without a db

llmware/configs.py, llmware/embeddings.py, setup.py, tests/embeddings/test_all_embedding_dbs.py, tests/embeddings/test_embeddings.py, tests/embeddings/utils.py
This PR
- Refactors the Qdrant client implementation to enable the use of an in-memory Qdrant instance, provide API keys and other params when instantiating Qdrant.
- Adds optional unit tests for the Qdrant implementation.
=> refactor: Qdrant vector database implementation

examples/Embedding/using_lance.py, llmware/configs.py, llmware/embeddings.py, setup.py, tests/embeddings/test_all_embedding_dbs.py, tests/run-tests.py
Hi , I am from LanceDB team and have added its integration enabling users to use our vectorDB. Added a working example under examples/Embedding/using_lance.py 
There was a minor error in run-tests.py , the Mongo Manager class was incorrectly called which was the reason why a default clone would fail the pytests. Have run the tests successfully now.
thanks !
=> LanceDB integration added / some bug fixes in testing scripts 

examples/Embedding/using_chromadb.py, llmware/configs.py, llmware/embeddings.py, tests/embeddings/test_all_embedding_dbs.py, tests/embeddings/test_embeddings.py
This pull request adds ```chroma``` support. And hence addresses issue #17 .
In particular, it
- updates LLMWareConfig
- updates EmbeddingHandler
- adds config class for ```chroma```
- adds an Embedding class for ```chroma```
- adds a unit test for ```chroma```
- adds example code.
=> Add chroma support

.devcontainer, devcontainer/README, devcontainer/devcontainer.json
=> Development containers

llmware/__init__.py, llmware/agents.py, llmware/configs.py, llmware/embeddings.py, llmware/library.py, llmware/model_configs.py, llmware/models.py, llmware/parsers.py, llmware/prompts.py, llmware/resources.py, llmware/retrieval.py, llmware/setup.py, llmware/status.py, llmware/util.py
This pull request addresses issues #405. Hence it adds docstrings to all modules and the package.
=> Add docstrings for all modules and the package

llmware/parsers.py
and produce the duplicat_files array, its all done by "math" and only one time, this speeds up the process by a lot
=> remove the loop to calculate the dup_counter 

llmware/agents.py, llmware/embeddings.py, llmware/library.py, llmware/status.py
This pull request adds class docstrings to all classes in the modules
- agents, 
- embeddings, 
- library, and 
- status.
It is linked to issue #448.
=> Add class docstrings to classes in the modules agents, embeddings, library, and status

llmware/model_configs.py, llmware/models.py, llmware/parsers.py, llmware/retrieval.py
I attached two new models by OpenAI, published in Jan 2024
=> adding gpt-3.5-turbo-0125 and gpt-4-0125-preview support

docker-compose-qdrant.yaml
Docker compose file to run llmware with qdrant as vector store
=> Qdrant docker compose

docs/index.md
This PR fixes typos in ``index.md``.
=> Fix typos in docs

docs/index.md
This PR enhances the install section.
In particular, it adds a subsection describing the manual install process with wheel files, and adds information on minimal install requirements and on the update frequency of wheels.
=> Add manual install and install requirements

examples/Embedding/using_pinecone_openai.bash, examples/Embedding/using_pinecone_openai.py
This PR adds an example to the ``examples`` directory which shows how you can combine ``Pinecone`` with ``OpenAI``.
=> Add example that combines Pinecone with OpenAI

README.md
Corrected a minor typo: "Where are are going" -> "Where are we going"
=> Update README.md (a small typo)

Quest/README.md
Ppl are finding difficulty in how to raise a PR, so, I edited the current readme and made it more easier to understand. Hope you like it.
=> Made the "Quest README" more meaningful

Quest/llmsoundware/README.md, Quest/llmsoundware/llmsoundware.py, Quest/llmsoundware/requirements.txt
LLMSoundWare is a LLMWare + Streamlit web application that takes an audio file as input, transcribes it using LLMware models, and performs various analyses on the transcription. The app provides insights into sentiment, named entities, topics, categories, intents, emotions, and summaries extracted from the audio content. Additionally, it features an interactive chatbot powered by the Dragon model from LLMware, allowing users to ask questions about the audio and its analysis.
=> Quest 011 Submission LLMSoundWare

Quest/LLMware-Lingua Public/.streamlit/config.toml, Quest/LLMware-Lingua Public/README.md, Quest/LLMware-Lingua Public/chatweb.py
This project is a LLMWare-based application for conversing with AI, featuring text-to-speech, document querying, and file upload capabilities. It helps users interact with AI models, access document information, and receive spoken responses.
This PR is based one submission of quest 011 on quine.
=> Quest 011 Submission by Chelseasingla1

docker-compose-redis-stack.yaml
Changed volume type from anonymous volume to named volume in docker-compose-redis-stack.yaml
=> modified redis compose volume

examples/Notebooks/NoteBook_Examples/Example_5.ipynb, examples/Notebooks/NoteBook_Examples/Example_6.ipynb
=> added notebook

docs/Gemfile
Reverts llmware-ai/llmware#858
=> Revert "Update Gemfile"

examples/Notebooks/README.md
This PR adds a section about marimo notebooks to the notebook documentation.
=> marimo section in notebooks docs

examples/Notebooks/NoteBook_Examples/text2sql-end-to-end-2-notebook.ipynb
Added notebook for text2sql end-to-end example (https://github.com/llmware-ai/llmware/blob/main/examples/SLIM-Agents/text2sql-end-to-end-2.py)
=> added text2sql end-to-end notebook

docs/community/troubleshooting.md
Added instructions to fix permission error when using git commands on the repository. Included official GitHub docs links to generate SSH keys and add them to GitHub.
=> Documentation

examples/Notebooks/NoteBook_Examples/example_1_create_first_library.ipynb, examples/Notebooks/NoteBook_Examples/example_2_build_embeddings.ipynb
=> example-1-create_first_library

examples/Notebooks/NoteBook_Examples/example_1_create_first_library.ipynb, examples/Notebooks/NoteBook_Examples/example_2_build_embeddings.ipynb, examples/Notebooks/NoteBook_Examples/example_3_prompts_and_models.ipynb
=> example-3-prompts_and_models

examples/Notebooks/NoteBook_Examples/example_1_create_first_library.ipynb, examples/Notebooks/NoteBook_Examples/example_2_build_embeddings.ipynb, examples/Notebooks/NoteBook_Examples/example_3_prompts_and_models.ipynb, examples/Notebooks/NoteBook_Examples/example_6_rag_multi_step_query.ipynb
=> example_6_rag_multi_step_query

examples/Notebooks/NoteBook_Examples/agent_with_custom_tables_example.ipynb
agent with custom tables use case
=> Uploading example notebook

examples/Models/using-azure-openai.py
Created 2 separate clients for each model, added deployment parameter in client constructors, added instructions as comments at the beginning of the example.
=> fixed example

llmware/prompts.py
Added `account_name` as an optional parameter with default value `"llmware"`. Passed in the optional parameter value into the `load_library()` call.
=> added account_name optional parameter

examples/Notebooks/NoteBook_Examples/using-slim-q-gen-notebook.ipynb
Added notebook for https://github.com/llmware-ai/llmware/blob/a58c2dc7ea94c1a8eef87bc0fd1cc34fb616c743/examples/SLIM-Agents/using-slim-q-gen.py
=> added slim-q-gen/dueling AIs notebook

fast_start/rag/example-6-rag-multi-step-query.py
=> changed i to j in nested loop

README.md
=> Added DevFest GIF and Prize Message

docs/index.md
Found a broken link when reading the guide.
=> Fix link to Platforms in index.md

docs/community/join_our_community.md, docs/community/need_help.md, docs/community/troubleshooting.md, docs/components/agent_inference_server.md, docs/components/agents.md, docs/components/components.md, docs/components/data_stores.md, docs/components/embedding_models.md, docs/components/gguf.md, docs/components/library.md, docs/components/model_catalog.md, docs/components/prompt_with_sources.md, docs/components/query.md, docs/components/rag_optimized_models.md, docs/components/release_history.md, docs/components/slim_models.md, docs/components/vector_databases.md, docs/components/whisper_cpp.md, docs/learn/advanced_techniques_for_rag.md, docs/learn/core_rag_scenarios_running_locally.md, docs/learn/integrated_voice_transcription_with_whisper_cpp.md, docs/learn/learn.md, docs/learn/other_topics.md, docs/learn/parsing_embedding_data_extraction.md, docs/learn/using_agents_functions_slim_models.md, docs/learn/using_quantized_gguf_models.md
Hey the hugging face icon is not rendering  in many of the files. I have updated that. let me know if any file left
=> Hugging Face Broken Url Fix: Fixed in all the files 

README.md
I have made some corrections to your repository to help clarify certain aspects. These improvements aim to enhance the overall understanding and usability of the project. I hope they contribute positively to your work!
=> (typo):i've made some corrections to your documentation which clarify things

README.md
Added a table of contents in readme to navigate things better.
=> add toc in readme.md for better navigation

README.md
I have made some corrections to your repository to help clarify certain aspects. These improvements aim to enhance the overall understanding and usability of the project. I hope they contribute positively to your work!
=> (typo):I've made some corrections to your documentation

docs/examples/use_cases.md
=> HuggingFace URL

docs/getting_started/getting_started.md
Fixed the broken link of supported platform in getting_started.md
This PR fixes #1089
=> Fixed broken link( supported platform) in getting_started.md

docs/examples/use_cases.md
The hugging face icon previously used doesn't match the other icons , so updated the icon from font awesome 
```
<i class="fa-solid fa-face-smiling-hands"></i>
```
For reference: [font-awesome](https://fontawesome.com/icons/face-smiling-hands?f=classic&s=solid)
=> Updated the hugging face icon

colab notebook/Agents_01.ipynb
Added google colab notebook for 1st agent example with documentation
=> feat: added colab notebook for agents

llmware/model_configs.py
=> feat: added new models (gpt o series, and gemini 1.5 pro)

llmware/resources.py
Fixes database write failures and malformed SQL queries
=> Fix: Critical SQLiteWriter database persistence and SQL formatting issues

README.md
This badge is generated by [https://discord-live-members-count-badge.vercel.app/](https://discord-live-members-count-badge.vercel.app/) created by Rohan Sharma (@RS-labhub)
=> added dynamic discord badge
